version: "2"

services:
  radio_api:
    image: kimbtechnologies/radio_api:latest
    container_name: radio_api
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./data/:/php-code/data/
      #- ./media/:/php-code/media/:ro # directory to add images for stations
    environment:
      - CONF_DOMAIN=http://radio.example.com/ # the domain where the system is hosted
      - CONF_ALLOWED_DOMAIN=all # allowed ips for access, list of DynDNS domainnames (divided by ','), or 'all' to allow all ips
      - CONF_CACHE_EXPIRE=1200 # cache expire time of ips, podcasts, ...
      - CONF_REDIS_HOST=redis # the redis hostname
      # - CONF_REDIS_PORT=6379 # default 6379
      # - CONF_REDIS_PASS= # default no auth
      - CONF_OWN_STREAM=true # fetch own streams at link below? (true/ false)
      - CONF_OWN_STREAM_JSON=http://stream.example.com/list.json # link where to fetch own streams, json like: { "key" : { name : "Test 1" }, "key2" : ... }
      - CONF_OWN_STREAM_URL=http://stream.example.com/?key= # url prefix to open own streamS, key are appended
      - CONF_PROXY_OWN_STREAM=false # use the proxy for the own streams (all own streams are proxied by the docker image)
    depends_on:
      - redis
  redis:
    image: redis:alpine
    container_name: radio_api_redis
    restart: always
    #volumes:
    #  - ./redis/:/data # redis is used as cache, so all data can be loaded from json files saved in radio_api
